# This file was generated by the {rix} R package v0.17.0 on 2025-06-07
# with following call:
# >rix(date = "2025-05-26",
#  > r_pkgs = c("nhanesA",
#  > "golem",
#  > "shiny",
#  > "cards",
#  > "gt",
#  > "echarts4r",
#  > "reactable",
#  > "dplyr",
#  > "tidyr",
#  > "purrr",
#  > "renv",
#  > "attachment",
#  > "openxlsx2",
#  > "devtools",
#  > "testthat",
#  > "dotenv",
#  > "markdown",
#  > "pool",
#  > "DBI",
#  > "lubridate",
#  > "stringr",
#  > "survey"),
#  > ide = "none",
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = FALSE,
#  > r_ver = "4.5.0")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-05-26.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      attachment
      cards
      DBI
      devtools
      dotenv
      dplyr
      echarts4r
      golem
      gt
      lubridate
      markdown
      nhanesA
      openxlsx2
      pool
      purrr
      reactable
      renv
      shiny
      stringr
      survey
      testthat
      tidyr;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
